language: c
# To build on OSX, switch the previous line to
# language: objective-c
env:
  matrix:
    - TYPE=cran
    - TYPE=tests

script:
  - if [ $TYPE == cran ]; then ( cd ..; R CMD check tikzDevice*.*.tar.gz --as-cran --no-build-vignettes --no-manual ); fi
  - if [ $TYPE == tests ]; then ( cd tests; ./unit_tests.R ); fi

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - OS=$(uname -s)
  - IsLinux() { [[ "$OS" == "Linux" ]]; }
  - ./travis-tool.sh bootstrap
  - IsSourceInstall() { [[ -n "${RELEASE}" ]]; }
  - if [ $TYPE == tests ]; then APT_EXTRA="texlive-xetex imagemagick"; export DISPLAY=:99.0; fi
  - if IsSourceInstall; then export FORCE_SOURCE_INSTALL=1; fi
install:
  - ./travis-tool.sh install_latex
  - if IsLinux; then sudo apt-get install --no-install-recommends $APT_EXTRA; fi
  - sh -e /etc/init.d/xvfb start
  - if IsSourceInstall; then (
      cd ~ &&
      svn co -q https://svn.r-project.org/R/${RELEASE}/ r-source &&
      cd r-source &&
      tools/rsync-recommended &&
      ./configure --enable-R-shlib &&
      make -j2 &&
      sudo make install
    ); fi
  - ./travis-tool.sh r_binary_install colorspace zoo RColorBrewer dichromat munsell labeling Formula sp mvtnorm TH.data sandwich gtable reshape2 scales proto quantreg Hmisc mapproj hexbin maptools multcomp filehash ggplot2 testthat
  - ( cd ..; R CMD build tikzDevice --no-build-vignettes --no-manual; R CMD INSTALL tikzDevice*.*.tar.gz )
  - ./travis-tool.sh dump_sysinfo
after_failure:
  - cat tikzDevice.Rcheck/00install.out || true
  - cat tikzDevice.Rcheck/00check.log || true
